#!/bin/bash
set -e

echo "Airflow and DWH database/user setup..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL

    CREATE USER ${AIRFLOW_USER} WITH PASSWORD '${AIRFLOW_PASSWORD}';
    CREATE DATABASE ${AIRFLOW_DB} OWNER ${AIRFLOW_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_DB} TO ${AIRFLOW_USER};

    \c ${AIRFLOW_DB} ${POSTGRES_USER}
    GRANT ALL ON SCHEMA public TO ${AIRFLOW_USER};
    REVOKE CREATE ON SCHEMA public FROM PUBLIC;

    CREATE USER ${DWH_USER} WITH PASSWORD '${DWH_PASSWORD}';
    \c postgres ${POSTGRES_USER}
    CREATE DATABASE ${DWH_DB} OWNER ${DWH_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${DWH_DB} TO ${DWH_USER};

    \c ${DWH_DB} ${POSTGRES_USER}
    CREATE EXTENSION IF NOT EXISTS postgis;
    CREATE EXTENSION IF NOT EXISTS unaccent;
EOSQL
echo "Airflow and DWH setup OK."